---
- name: Install cockpit
  community.general.pacman:
    name:
      - cockpit-machines
    state: present
  become: true

- name: Enable cockpit socket
  ansible.builtin.systemd:
    name: cockpit.socket
    state: started
    enabled: true
  become: true
...
