---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    pacman:
      update_cache: yes

  - name: install apache package
    pacman:
      name: apache
      state: latest

  - name: install vim package
    pacman:
      name: vim
