---
- hosts: localhost
  roles:
    - role: alacritty
    - role: gnupg
    - role: browsers
      tags: ['firefox']
    - role: dotfiles
    - role: nvim
      vars:
        vim:
          dir: "/home/{{ user.name }}/.config/nvim"
    - role: bluetooth
