---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    pacman:
      update_cache: yes

  - name: remove apache package
    pacman:
      name: apache
      state: absent

  - name: remove vim package
    pacman:
      name: vim
      state: absent
