---
- name: Install chezmoi
  become: yes
  pacman:
    name: chezmoi
    state: present
  when: dotfiles is defined

- name: Clone user's dotfiles
  git:
    repo: "{{ dotfiles.url }}"
    dest: /home/{{ user.name }}/{{ dotfiles.destination }}
    update: no
  when: dotfiles is defined
  become: yes
  become_user: "{{ user.name }}"

- name: Install user's dotfiles
  command: chezmoi apply --force
  when: dotfiles is defined
  become: yes
  become_user: "{{ user.name }}"
