---
- name: Install chezmoi
  community.general.pacman:
    name: chezmoi
    state: present
  become: true

- name: Clone user's dotfiles
  ansible.builtin.git:
    repo: "{{ dotfiles.url }}"
    dest: /home/{{ user.name }}/{{ dotfiles.destination }}
    update: false
  become: true
  become_user: "{{ user.name }}"

- name: Install user's dotfiles
  ansible.builtin.command: chezmoi apply --force
  when: dotfiles is defined
  become: true
  become_user: "{{ user.name }}"
