---
- name: Install bluez
  community.general.pacman:
    name:
      - bluez
      - bluez-utils
    state: present
  become: true

- name: Install blueman
  community.general.pacman:
    name:
      - blueman
    state: present
  become: true

- name: Enable bluetooth service
  ansible.builtin.systemd:
    name: bluetooth
    enabled: true
  become: true
