---
- name: Install bluez
  pacman:
    name: 
      - bluez
      - bluez-utils
    state: present

- name: Install blueman
  pacman:
    name:
      - blueman
    state: present

- name: Enable bluetooth service
  ansible.builtin.systemd:
    name: bluetooth
    enabled: true
