---
- name: Install alacritty
  community.general.pacman:
    name: alacritty
    state: present
  become: true

- name: Install tmux
  community.general.pacman:
    name: tmux
    state: present
  become: true
