---
- name: Install docker
  community.general.pacman:
    name: docker
    state: present
  become: true

- name: Install docker-compose
  community.general.pacman:
    name: docker-compose
    state: present
  become: true

- name: Enable docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
  become: true

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ user.name }}"
    groups: docker
    append: true
  become: true
...
